using UnityEngine;

[CreateAssetMenu(fileName = "SimulationRules", menuName = "Simulation/Rules")]
public sealed class SimulationRules : ScriptableObject
{
    public enum EpsilonSchedule { Exponential = 0, PlateauByFitness = 1 }

    public readonly struct RulesFrame
    {
        public readonly float EatEnergyFood;
        public readonly float RestHealRate;
        public readonly int FoodRegenBurst;
        public readonly float StarvationDamage;
        public readonly float StarvationEnergyReturn;
        public readonly float StarvationThreshold;
        public readonly float TerminalPenalty;
        public readonly float InterruptionReward;
        public readonly float FailureReward;
        public readonly float PpoClipEpsilon;
        public readonly float RewardClipSigma;
        public readonly float CriticLearningRate;
        public readonly float CriticHuberDelta;
        public readonly float ExplorationEpsilonScale;
        public readonly float EpsilonDecayPerStep;
        public readonly float MinEpsilon;
        public readonly float MinLearningRate;
        public readonly float LrDecayPerSecond;
        public readonly float FitnessSurvivalWeight;
        public readonly float FitnessSurvivalTau;
        public readonly float FitnessRateWindow;
        public readonly float FitnessMinLifetime;
        public readonly float FitnessFoodRateWeight;
        public readonly float FitnessReproduceRateWeight;
        public readonly float FitnessDamageRateWeight;
        public readonly float TerminalFitnessSensitivity;
        public readonly float TerminalPenaltyMinScale;
        public readonly float TerminalPenaltyMaxScale;
        public readonly int TournamentSize;
        public readonly float GenerationInterval;
        public readonly float EliteFraction;
        public readonly float BasalEnergyDrain;
        public readonly float TerrainBiasWeight;
        public readonly float TerrainCostWeight;
        public readonly float TerrainSlopeWeight;
        public readonly float TerrainWaterWeight;
        public readonly float MaxCycleDt;
        public readonly float ModifierDecayTau;
        public readonly float EatRange;
        public readonly float InfeasibleActionHealthPenalty;
        public readonly float ThreatenDuration;
        public readonly float ShareFoodDuration;
        public readonly float CommandWatchdogGrace;
        public readonly float RewardStdFloor;
        public readonly float RestHealEnergyCost;
        public readonly float SpeechEnergyCost;
        public readonly float ThreatenEnergyCost;
        public readonly float DangerLowFraction;
        public readonly float DangerMidFraction;
        public readonly float DangerCritFraction;
        public readonly float BreedMarginFraction;
        public readonly float ShareFoodTransferFraction;
        public readonly float ShareFoodVictimRatio;
        public readonly float FleeDistanceMul;
        public readonly float RememberPointMinSpacing;
        public readonly float ThreatenRangeMul;
        public readonly float GeneSpeedCostExponent;
        public readonly float GeneEnergyCapacityUpkeep;
        public readonly float GeneDetectionUpkeep;
        public readonly float GeneMinBasalMul;
        public readonly float InitBiasRange;
        public readonly bool PeriodicGenotypeOverwrite;
        public readonly float CodonsPerSecond;
        public readonly int MaxCodonsPerCycle;
        public readonly int DormantCodons;
        public readonly float ContactRadius;
        public readonly float IntegrityDecayPerSecond;
        public readonly float IntegrityMutationScale;
        public readonly float IntegrityRemoveThreshold;
        public readonly float VerticalTransmissionChance;
        public readonly float VerticalEndogenousMutationRate;
        public readonly float VerticalTableMutationChance;
        public readonly int VirologyMaxSegments;
        public readonly int RndSamplesPerSweep;
        public readonly float RndLearningRate;
        public readonly float RndNormAlpha;
        public readonly float EpsilonPlateauFitnessThreshold;
        public readonly float EpsilonPlateauDrop;
        public readonly float EpsilonPlateauMinScale;
        public readonly float EpsilonPlateauThresholdGrowth;
        public readonly float EpsilonPlateauThresholdStep;
        public readonly float ActionTraceHorizon;
        public readonly float ReservoirSpectralRadius;
        public readonly float BlockedSpeedThreshold;
        public readonly float BlockedSeconds;
        public readonly float DigestRateRest;
        public readonly float DigestRateActive;
        public readonly float DigestEffRest;
        public readonly float DigestEffActive;
        public readonly float StomachCapacityFraction;
        public readonly float WellFedGainPerSecond;
        public readonly float WellFedDecayPerSecond;
        public readonly float WellFedBasalReduction;
        public readonly float DriveEnergyWeight;
        public readonly float DriveHealthWeight;
        public readonly float DriveRewardWeight;
        public readonly float DriveShapingWeight;
        public readonly float EventReproduceReward;
        public readonly float InfeasibleActionReward;
        public readonly float GoalFoodWeight;
        public readonly float GoalEnergyWeight;
        public readonly float GoalRestWeight;
        public readonly float CoordCuriosityWeight;
        public readonly float ExecGammaPerSecond;
        public readonly float CoordGammaPerSecond;
        public readonly float SynergyWindow;
        public readonly float RestAfterEatDigestMul;
        public readonly float NestRestHealMul;
        public readonly float NestRestDamageMul;
        public readonly float NightStart;
        public readonly float NightEnd;
        public readonly float NightOutsideDrainMul;
        public readonly float ThreatenAttackMul;
        public readonly float GroupAttackBonus;
        public readonly float GroupAttackRadius;
        public readonly float GroupAttackWindow;
        public readonly int GroupAttackMaxCount;
        public readonly float WarnWindow;
        public readonly float WarnDangerThreshold;
        public readonly float WarnedFleeSpeedMul;
        public readonly float SpeechRadius;
        public readonly float MovePauseMin;
        public readonly float MovePauseMax;
        public readonly float AttackMoveMaxDuration;
        public readonly float FoodMinNutritionFraction;
        public readonly float FoodMaturityPerSecond;
        public readonly float FoodGrowthRate;
        public readonly float FoodSeedFraction;
        public readonly float FoodChunkCapacity;
        public readonly float SeasonAmplitude;
        public readonly float SeasonPeriod;
        public readonly float EcologyTickInterval;
        public readonly float EcologyMaxStep;
        public readonly float LargeFoodChance;
        public readonly float LargeFoodEnergy;
        public readonly float LargeFoodWindow;
        public readonly float ToxicNutritionMul;
        public readonly float ToxicDamage;
        public readonly float EatSecondsPerEnergy;
        public readonly float CorpseMinEnergy;
        public readonly int CorpseSearchCells;
        public readonly float CorpseSpoilTau;
        public readonly float NestEatPortion;
        public readonly float NestStorageNorm;
        public readonly float CarrySpeedMul;
        public readonly int PlannerCandidates;
        public readonly float PlannerSectorHalf;
        public readonly float PlannerMinRadiusFraction;
        public readonly float PlannerMoveCostWeight;
        public readonly float PlannerFoodWeight;
        public readonly float PlannerDangerWeight;
        public readonly float PlannerTargetWeight;
        public readonly float PlannerAlignWeight;
        public readonly float PlannerCurvatureMin;
        public readonly float PlannerCurvatureScale;
        public readonly float PlannerRadiusMax;
        public readonly int PlannerMaxReplans;
        public readonly float PlannerReplanAngle;
        public readonly float NestRadius;
        public readonly int NestMapSize;
        public readonly float NestMapCellSize;
        public readonly float NestMapMaxValue;
        public readonly float NestFoodPeakMin;
        public readonly float NestFoodMark;
        public readonly float NestDangerMark;
        public readonly float AlarmTau;
        public readonly int AlarmHuntMinMembers;
        public readonly float AlarmFromDamage;
        public readonly float AlarmHuntBias;
        public readonly float AlarmSurviveBias;
        public readonly float AlarmFleeBias;
        public readonly float SkipWeakHpFraction;
        public readonly int SkipCrowdCount;
        public readonly float CrowdRadius;
        public readonly float SpeechSpreadRadius;
        public readonly float BiteTransmissionChance;
        public readonly int ImmuneMemorySize;
        public readonly int ImmuneHammingThreshold;
        public readonly float FeverIntegrityMul;
        public readonly float FeverDrainMul;
        public readonly int CaptureLength;
        public readonly float CarryPoiThreshold;
        public readonly float BlindStrength;
        public readonly float FrenzyDamageMul;
        public readonly float FrenzyHuntBias;
        public readonly float FrenzyFleeSuppress;
        public readonly float LethargySlow;
        public readonly int   EpsilonScheduleMode;
        public readonly float ActionTraceInvLogNorm;
        public readonly float ReservoirHz;

        public RulesFrame(SimulationRules r)
        {
            EatEnergyFood = r.eatEnergyFood;
            RestHealRate = r.restHealRate;
            FoodRegenBurst = r.foodRegenBurst;
            StarvationDamage = r.starvationDamage;
            StarvationEnergyReturn = r.starvationEnergyReturn;
            StarvationThreshold = r.starvationThreshold;
            TerminalPenalty = r.terminalPenalty;
            InterruptionReward = r.interruptionReward;
            FailureReward = r.failureReward;
            PpoClipEpsilon = r.ppoClipEpsilon;
            RewardClipSigma = r.rewardClipSigma;
            CriticLearningRate = r.criticLearningRate;
            CriticHuberDelta = r.criticHuberDelta;
            ExplorationEpsilonScale = r.explorationEpsilonScale;
            EpsilonDecayPerStep = r.epsilonDecayPerStep;
            MinEpsilon = r.minEpsilon;
            MinLearningRate = r.minLearningRate;
            LrDecayPerSecond = r.lrDecayPerSecond;
            FitnessSurvivalWeight = r.fitnessSurvivalWeight;
            FitnessSurvivalTau = r.fitnessSurvivalTau;
            FitnessRateWindow = r.fitnessRateWindow;
            FitnessMinLifetime = r.fitnessMinLifetime;
            FitnessFoodRateWeight = r.fitnessFoodRateWeight;
            FitnessReproduceRateWeight = r.fitnessReproduceRateWeight;
            FitnessDamageRateWeight = r.fitnessDamageRateWeight;
            TerminalFitnessSensitivity = r.terminalFitnessSensitivity;
            TerminalPenaltyMinScale = r.terminalPenaltyMinScale;
            TerminalPenaltyMaxScale = r.terminalPenaltyMaxScale;
            TournamentSize = r.tournamentSize;
            GenerationInterval = r.generationInterval;
            EliteFraction = r.eliteFraction;
            BasalEnergyDrain = r.basalEnergyDrain;
            TerrainBiasWeight = r.terrainBiasWeight;
            TerrainCostWeight = r.terrainCostWeight;
            TerrainSlopeWeight = r.terrainSlopeWeight;
            TerrainWaterWeight = r.terrainWaterWeight;
            MaxCycleDt = r.maxCycleDt;
            ModifierDecayTau = r.modifierDecayTau;
            EatRange = r.eatRange;
            InfeasibleActionHealthPenalty = r.infeasibleActionHealthPenalty;
            ThreatenDuration = r.threatenDuration;
            ShareFoodDuration = r.shareFoodDuration;
            CommandWatchdogGrace = r.commandWatchdogGrace;
            RewardStdFloor = r.rewardStdFloor;
            RestHealEnergyCost = r.restHealEnergyCost;
            SpeechEnergyCost = r.speechEnergyCost;
            ThreatenEnergyCost = r.threatenEnergyCost;
            DangerLowFraction = r.dangerLowFraction;
            DangerMidFraction = r.dangerMidFraction;
            DangerCritFraction = r.dangerCritFraction;
            BreedMarginFraction = r.breedMarginFraction;
            ShareFoodTransferFraction = r.shareFoodTransferFraction;
            ShareFoodVictimRatio = r.shareFoodVictimRatio;
            FleeDistanceMul = r.fleeDistanceMul;
            RememberPointMinSpacing = r.rememberPointMinSpacing;
            ThreatenRangeMul = r.threatenRangeMul;
            GeneSpeedCostExponent = r.geneSpeedCostExponent;
            GeneEnergyCapacityUpkeep = r.geneEnergyCapacityUpkeep;
            GeneDetectionUpkeep = r.geneDetectionUpkeep;
            GeneMinBasalMul = r.geneMinBasalMul;
            InitBiasRange = r.initBiasRange;
            PeriodicGenotypeOverwrite = r.periodicGenotypeOverwrite;
            CodonsPerSecond = r.codonsPerSecond;
            MaxCodonsPerCycle = r.maxCodonsPerCycle;
            DormantCodons = r.dormantCodons;
            ContactRadius = r.contactRadius;
            IntegrityDecayPerSecond = r.integrityDecayPerSecond;
            IntegrityMutationScale = r.integrityMutationScale;
            IntegrityRemoveThreshold = r.integrityRemoveThreshold;
            VerticalTransmissionChance = r.verticalTransmissionChance;
            VerticalEndogenousMutationRate = r.verticalEndogenousMutationRate;
            VerticalTableMutationChance = r.verticalTableMutationChance;
            VirologyMaxSegments = r.virologyMaxSegments;
            RndSamplesPerSweep = r.rndSamplesPerSweep;
            RndLearningRate = r.rndLearningRate;
            RndNormAlpha = r.rndNormAlpha;
            EpsilonPlateauFitnessThreshold = r.epsilonPlateauFitnessThreshold;
            EpsilonPlateauDrop = r.epsilonPlateauDrop;
            EpsilonPlateauMinScale = r.epsilonPlateauMinScale;
            EpsilonPlateauThresholdGrowth = r.epsilonPlateauThresholdGrowth;
            EpsilonPlateauThresholdStep = r.epsilonPlateauThresholdStep;
            ActionTraceHorizon = r.actionTraceHorizon;
            ReservoirSpectralRadius = r.reservoirSpectralRadius;
            BlockedSpeedThreshold = r.blockedSpeedThreshold;
            BlockedSeconds = r.blockedSeconds;
            DigestRateRest = r.digestRateRest;
            DigestRateActive = r.digestRateActive;
            DigestEffRest = r.digestEffRest;
            DigestEffActive = r.digestEffActive;
            StomachCapacityFraction = r.stomachCapacityFraction;
            WellFedGainPerSecond = r.wellFedGainPerSecond;
            WellFedDecayPerSecond = r.wellFedDecayPerSecond;
            WellFedBasalReduction = r.wellFedBasalReduction;
            DriveEnergyWeight = r.driveEnergyWeight;
            DriveHealthWeight = r.driveHealthWeight;
            DriveRewardWeight = r.driveRewardWeight;
            DriveShapingWeight = r.driveShapingWeight;
            EventReproduceReward = r.eventReproduceReward;
            InfeasibleActionReward = r.infeasibleActionReward;
            GoalFoodWeight = r.goalFoodWeight;
            GoalEnergyWeight = r.goalEnergyWeight;
            GoalRestWeight = r.goalRestWeight;
            CoordCuriosityWeight = r.coordCuriosityWeight;
            ExecGammaPerSecond = r.execGammaPerSecond;
            CoordGammaPerSecond = r.coordGammaPerSecond;
            SynergyWindow = r.synergyWindow;
            RestAfterEatDigestMul = r.restAfterEatDigestMul;
            NestRestHealMul = r.nestRestHealMul;
            NestRestDamageMul = r.nestRestDamageMul;
            NightStart = r.nightStart;
            NightEnd = r.nightEnd;
            NightOutsideDrainMul = r.nightOutsideDrainMul;
            ThreatenAttackMul = r.threatenAttackMul;
            GroupAttackBonus = r.groupAttackBonus;
            GroupAttackRadius = r.groupAttackRadius;
            GroupAttackWindow = r.groupAttackWindow;
            GroupAttackMaxCount = r.groupAttackMaxCount;
            WarnWindow = r.warnWindow;
            WarnDangerThreshold = r.warnDangerThreshold;
            WarnedFleeSpeedMul = r.warnedFleeSpeedMul;
            SpeechRadius = r.speechRadius;
            MovePauseMin = r.movePauseMin;
            MovePauseMax = r.movePauseMax;
            AttackMoveMaxDuration = r.attackMoveMaxDuration;
            FoodMinNutritionFraction = r.foodMinNutritionFraction;
            FoodMaturityPerSecond = r.foodMaturityPerSecond;
            FoodGrowthRate = r.foodGrowthRate;
            FoodSeedFraction = r.foodSeedFraction;
            FoodChunkCapacity = r.foodChunkCapacity;
            SeasonAmplitude = r.seasonAmplitude;
            SeasonPeriod = r.seasonPeriod;
            EcologyTickInterval = r.ecologyTickInterval;
            EcologyMaxStep = r.ecologyMaxStep;
            LargeFoodChance = r.largeFoodChance;
            LargeFoodEnergy = r.largeFoodEnergy;
            LargeFoodWindow = r.largeFoodWindow;
            ToxicNutritionMul = r.toxicNutritionMul;
            ToxicDamage = r.toxicDamage;
            EatSecondsPerEnergy = r.eatSecondsPerEnergy;
            CorpseMinEnergy = r.corpseMinEnergy;
            CorpseSearchCells = r.corpseSearchCells;
            CorpseSpoilTau = r.corpseSpoilTau;
            NestEatPortion = r.nestEatPortion;
            NestStorageNorm = r.nestStorageNorm;
            CarrySpeedMul = r.carrySpeedMul;
            PlannerCandidates = r.plannerCandidates;
            PlannerSectorHalf = r.plannerSectorHalf;
            PlannerMinRadiusFraction = r.plannerMinRadiusFraction;
            PlannerMoveCostWeight = r.plannerMoveCostWeight;
            PlannerFoodWeight = r.plannerFoodWeight;
            PlannerDangerWeight = r.plannerDangerWeight;
            PlannerTargetWeight = r.plannerTargetWeight;
            PlannerAlignWeight = r.plannerAlignWeight;
            PlannerCurvatureMin = r.plannerCurvatureMin;
            PlannerCurvatureScale = r.plannerCurvatureScale;
            PlannerRadiusMax = r.plannerRadiusMax;
            PlannerMaxReplans = r.plannerMaxReplans;
            PlannerReplanAngle = r.plannerReplanAngle;
            NestRadius = r.nestRadius;
            NestMapSize = r.nestMapSize;
            NestMapCellSize = r.nestMapCellSize;
            NestMapMaxValue = r.nestMapMaxValue;
            NestFoodPeakMin = r.nestFoodPeakMin;
            NestFoodMark = r.nestFoodMark;
            NestDangerMark = r.nestDangerMark;
            AlarmTau = r.alarmTau;
            AlarmHuntMinMembers = r.alarmHuntMinMembers;
            AlarmFromDamage = r.alarmFromDamage;
            AlarmHuntBias = r.alarmHuntBias;
            AlarmSurviveBias = r.alarmSurviveBias;
            AlarmFleeBias = r.alarmFleeBias;
            SkipWeakHpFraction = r.skipWeakHpFraction;
            SkipCrowdCount = r.skipCrowdCount;
            CrowdRadius = r.crowdRadius;
            SpeechSpreadRadius = r.speechSpreadRadius;
            BiteTransmissionChance = r.biteTransmissionChance;
            ImmuneMemorySize = r.immuneMemorySize;
            ImmuneHammingThreshold = r.immuneHammingThreshold;
            FeverIntegrityMul = r.feverIntegrityMul;
            FeverDrainMul = r.feverDrainMul;
            CaptureLength = r.captureLength;
            CarryPoiThreshold = r.carryPoiThreshold;
            BlindStrength = r.blindStrength;
            FrenzyDamageMul = r.frenzyDamageMul;
            FrenzyHuntBias = r.frenzyHuntBias;
            FrenzyFleeSuppress = r.frenzyFleeSuppress;
            LethargySlow = r.lethargySlow;
            EpsilonScheduleMode   = (int)r.epsilonScheduleMode;
            ActionTraceInvLogNorm = 1f / Mathf.Log(1f + Mathf.Max(r.actionTraceHorizon, 1e-3f));
            ReservoirHz           = r.reservoirHz;
        }
    }

    private static RulesFrame _frame;
    public static ref readonly RulesFrame Frame => ref _frame;

    public static void CaptureFrame() => _frame = new RulesFrame(Active);

    public static void Bind(SimulationRules rules)
    {
        if (rules != null) _active = rules;
        CaptureFrame();
    }

    [SerializeField] private float eatEnergyFood = 20f;
    [SerializeField] private float restHealRate = 5f;
    [SerializeField] private int foodRegenBurst = 8;
    [SerializeField] private float starvationDamage = 12f;
    [SerializeField] private float starvationEnergyReturn = 5f;
    [SerializeField] private float starvationThreshold = 5f;
    [SerializeField] private float terminalPenalty = -1f;
    [SerializeField] private float interruptionReward = -0.1f;
    [SerializeField] private float failureReward = -0.2f;
    [SerializeField] private float ppoClipEpsilon = 0.2f;
    [SerializeField] private float rewardClipSigma = 5f;
    [SerializeField] private float criticLearningRate = 0.004f;
    [SerializeField] private float criticHuberDelta = 1f;
    [SerializeField] private float explorationEpsilonScale = 1f;
    [SerializeField] private float epsilonDecayPerStep = 5e-5f;
    [SerializeField] private float minEpsilon = 0.01f;
    [SerializeField] private float minLearningRate = 1e-3f;
    [SerializeField] private float lrDecayPerSecond = 5e-4f;
    [SerializeField] private float fitnessSurvivalWeight = 10f;
    [SerializeField] private float fitnessSurvivalTau = 60f;
    [SerializeField] private float fitnessRateWindow = 60f;
    [SerializeField] private float fitnessMinLifetime = 10f;
    [SerializeField] private float fitnessFoodRateWeight = 6f;
    [SerializeField] private float fitnessReproduceRateWeight = 12f;
    [SerializeField] private float fitnessDamageRateWeight = 0.05f;
    [SerializeField] private float terminalFitnessSensitivity = 0.5f;
    [SerializeField] private float terminalPenaltyMinScale = 0.25f;
    [SerializeField] private float terminalPenaltyMaxScale = 2f;
    [SerializeField] private int tournamentSize = 3;
    [SerializeField] private float generationInterval = 60f;
    [SerializeField] private float eliteFraction = 0.1f;
    [SerializeField] private float basalEnergyDrain = 0.5f;
    [SerializeField] private float terrainBiasWeight = 0.45f;
    [SerializeField] private float terrainCostWeight = 1f;
    [SerializeField] private float terrainSlopeWeight = 0.8f;
    [SerializeField] private float terrainWaterWeight = 0.6f;
    [SerializeField] private float maxCycleDt = 3f;
    [SerializeField] private float modifierDecayTau = 85f;
    [SerializeField] private float eatRange = 2f;
    [SerializeField] private float infeasibleActionHealthPenalty = 0f;
    [SerializeField] private float threatenDuration = 0.8f;
    [SerializeField] private float shareFoodDuration = 0.5f;
    [SerializeField] private float commandWatchdogGrace = 0.1f;
    [SerializeField] private float rewardStdFloor = 0.05f;
    [SerializeField] private float restHealEnergyCost = 0.5f;
    [SerializeField] private float speechEnergyCost = 5f;
    [SerializeField] private float threatenEnergyCost = 3f;
    [SerializeField] private float dangerLowFraction = 0.5f;
    [SerializeField] private float dangerMidFraction = 0.25f;
    [SerializeField] private float dangerCritFraction = 0.1f;
    [SerializeField] private float breedMarginFraction = 0.5f;
    [SerializeField] private float shareFoodTransferFraction = 0.2f;
    [SerializeField] private float shareFoodVictimRatio = 0.8f;
    [SerializeField] private float fleeDistanceMul = 1.5f;
    [SerializeField] private float rememberPointMinSpacing = 10f;
    [SerializeField] private float threatenRangeMul = 2f;
    [SerializeField] private float geneSpeedCostExponent = 2f;
    [SerializeField] private float geneEnergyCapacityUpkeep = 0.5f;
    [SerializeField] private float geneDetectionUpkeep = 0.3f;
    [SerializeField] private float geneMinBasalMul = 0.3f;
    [SerializeField] private float initBiasRange = 0.1f;
    [SerializeField] private bool periodicGenotypeOverwrite = false;
    [SerializeField] private float codonsPerSecond = 1f;
    [SerializeField] private int maxCodonsPerCycle = 4;
    [SerializeField] private int dormantCodons = 8;
    [SerializeField] private float contactRadius = 3f;
    [SerializeField] private float integrityDecayPerSecond = 0.002f;
    [SerializeField] private float integrityMutationScale = 0.05f;
    [SerializeField] private float integrityRemoveThreshold = 0.1f;
    [SerializeField] private float verticalTransmissionChance = 0.5f;
    [SerializeField] private float verticalEndogenousMutationRate = 0.02f;
    [SerializeField] private float verticalTableMutationChance = 0.05f;
    [SerializeField] private int virologyMaxSegments = 32;
    [SerializeField] private int rndSamplesPerSweep = 128;
    [SerializeField] private float rndLearningRate = 0.01f;
    [SerializeField] private float rndNormAlpha = 0.01f;
    [SerializeField] private float epsilonPlateauFitnessThreshold = 5f;
    [SerializeField] private float epsilonPlateauDrop = 0.7f;
    [SerializeField] private float epsilonPlateauMinScale = 0.1f;
    [SerializeField] private float epsilonPlateauThresholdGrowth = 1.2f;
    [SerializeField] private float epsilonPlateauThresholdStep = 0f;
    [SerializeField] private float actionTraceHorizon = 120f;
    [SerializeField] private float reservoirSpectralRadius = 0.9f;
    [SerializeField] private float reservoirHz = 0f;
    [SerializeField] private float translationLutMaxDistanceSq = 64f;
    [SerializeField] private float blockedSpeedThreshold = 0.15f;
    [SerializeField] private float blockedSeconds = 0.75f;
    [SerializeField] private float digestRateRest = 4f;
    [SerializeField] private float digestRateActive = 1.5f;
    [SerializeField] private float digestEffRest = 0.95f;
    [SerializeField] private float digestEffActive = 0.7f;
    [SerializeField] private float stomachCapacityFraction = 0.6f;
    [SerializeField] private float wellFedGainPerSecond = 0.05f;
    [SerializeField] private float wellFedDecayPerSecond = 0.02f;
    [SerializeField] private float wellFedBasalReduction = 0.3f;
    [SerializeField] private float driveEnergyWeight = 1f;
    [SerializeField] private float driveHealthWeight = 1f;
    [SerializeField] private float driveRewardWeight = 0.1f;
    [SerializeField] private float driveShapingWeight = 1f;
    [SerializeField] private float eventReproduceReward = 1f;
    [SerializeField] private float infeasibleActionReward = -0.15f;
    [SerializeField] private float goalFoodWeight = 0.3f;
    [SerializeField] private float goalEnergyWeight = 1f;
    [SerializeField] private float goalRestWeight = 0.05f;
    [SerializeField] private float coordCuriosityWeight = 0.15f;
    [SerializeField] private float execGammaPerSecond = 0.9f;
    [SerializeField] private float coordGammaPerSecond = 0.97f;
    [SerializeField] private float synergyWindow = 6f;
    [SerializeField] private float restAfterEatDigestMul = 1.5f;
    [SerializeField] private float nestRestHealMul = 1.5f;
    [SerializeField] private float nestRestDamageMul = 0.5f;
    [SerializeField] private float nightStart = 0.75f;
    [SerializeField] private float nightEnd = 0.25f;
    [SerializeField] private float nightOutsideDrainMul = 1.5f;
    [SerializeField] private float threatenAttackMul = 1.3f;
    [SerializeField] private float groupAttackBonus = 0.25f;
    [SerializeField] private float groupAttackRadius = 4f;
    [SerializeField] private float groupAttackWindow = 2f;
    [SerializeField] private int groupAttackMaxCount = 4;
    [SerializeField] private float warnWindow = 4f;
    [SerializeField] private float warnDangerThreshold = 0.5f;
    [SerializeField] private float warnedFleeSpeedMul = 1.3f;
    [SerializeField] private float speechRadius = 12f;
    [SerializeField] private float movePauseMin = 0.3f;
    [SerializeField] private float movePauseMax = 1.2f;
    [SerializeField] private float attackMoveMaxDuration = 2f;
    [SerializeField] private float foodMinNutritionFraction = 0.3f;
    [SerializeField] private float foodMaturityPerSecond = 0.01f;
    [SerializeField] private float foodGrowthRate = 0.02f;
    [SerializeField] private float foodSeedFraction = 0.02f;
    [SerializeField] private float foodChunkCapacity = 40f;
    [SerializeField] private float seasonAmplitude = 0.3f;
    [SerializeField] private float seasonPeriod = 600f;
    [SerializeField] private float ecologyTickInterval = 0.5f;
    [SerializeField] private float ecologyMaxStep = 2f;
    [SerializeField] private float largeFoodChance = 0.05f;
    [SerializeField] private float largeFoodEnergy = 60f;
    [SerializeField] private float largeFoodWindow = 3f;
    [SerializeField] private float toxicNutritionMul = 0.5f;
    [SerializeField] private float toxicDamage = 15f;
    [SerializeField] private float eatSecondsPerEnergy = 0.05f;
    [SerializeField] private float corpseMinEnergy = 2f;
    [SerializeField] private int corpseSearchCells = 3;
    [SerializeField] private float corpseSpoilTau = 120f;
    [SerializeField] private float nestEatPortion = 15f;
    [SerializeField] private float nestStorageNorm = 200f;
    [SerializeField] private float carrySpeedMul = 0.8f;
    [SerializeField] private int plannerCandidates = 8;
    [SerializeField] private float plannerSectorHalf = 0.9f;
    [SerializeField] private float plannerMinRadiusFraction = 0.6f;
    [SerializeField] private float plannerMoveCostWeight = 1f;
    [SerializeField] private float plannerFoodWeight = 0.5f;
    [SerializeField] private float plannerDangerWeight = 1f;
    [SerializeField] private float plannerTargetWeight = 2f;
    [SerializeField] private float plannerAlignWeight = 0.3f;
    [SerializeField] private float plannerCurvatureMin = 0.1f;
    [SerializeField] private float plannerCurvatureScale = 0.35f;
    [SerializeField] private float plannerRadiusMax = 30f;
    [SerializeField] private int plannerMaxReplans = 2;
    [SerializeField] private float plannerReplanAngle = 0.6f;
    [SerializeField] private float nestRadius = 8f;
    [SerializeField] private int nestMapSize = 64;
    [SerializeField] private float nestMapCellSize = 4f;
    [SerializeField] private float nestMapMaxValue = 10f;
    [SerializeField] private float[] colonyChannelTau = { 120f, 60f };
    [SerializeField] private float colonyChannelDefaultTau = 60f;
    [SerializeField] private float nestFoodPeakMin = 0.2f;
    [SerializeField] private float nestFoodMark = 0.5f;
    [SerializeField] private float nestDangerMark = 5f;
    [SerializeField] private float alarmTau = 20f;
    [SerializeField] private int alarmHuntMinMembers = 5;
    [SerializeField] private float alarmFromDamage = 2f;
    [SerializeField] private float alarmHuntBias = 1.5f;
    [SerializeField] private float alarmSurviveBias = 1.5f;
    [SerializeField] private float alarmFleeBias = 1.5f;
    [SerializeField] private float skipWeakHpFraction = 0.3f;
    [SerializeField] private int skipCrowdCount = 3;
    [SerializeField] private float crowdRadius = 4f;
    [SerializeField] private float speechSpreadRadius = 10f;
    [SerializeField] private float biteTransmissionChance = 0.2f;
    [SerializeField] private int immuneMemorySize = 8;
    [SerializeField] private int immuneHammingThreshold = 10;
    [SerializeField] private float feverIntegrityMul = 4f;
    [SerializeField] private float feverDrainMul = 0.5f;
    [SerializeField] private int captureLength = 6;
    [SerializeField] private float carryPoiThreshold = 0.2f;
    [SerializeField] private float blindStrength = 0.7f;
    [SerializeField] private float frenzyDamageMul = 0.5f;
    [SerializeField] private float frenzyHuntBias = 1f;
    [SerializeField] private float frenzyFleeSuppress = 1f;
    [SerializeField] private float lethargySlow = 0.5f;
    [SerializeField] private EpsilonSchedule epsilonScheduleMode = EpsilonSchedule.Exponential;
    [SerializeField] private float[] biomeFertility = { 1f, 0.6f, 0.3f, 1.2f };
    [SerializeField] private float[] biomeToxicity  = { 0.02f, 0.08f, 0.25f, 0.04f };

    public float EatEnergyFood => eatEnergyFood;
    public float RestHealRate => restHealRate;
    public int FoodRegenBurst => foodRegenBurst;
    public float StarvationDamage => starvationDamage;
    public float StarvationEnergyReturn => starvationEnergyReturn;
    public float StarvationThreshold => starvationThreshold;
    public float TerminalPenalty => terminalPenalty;
    public float InterruptionReward => interruptionReward;
    public float FailureReward => failureReward;
    public float PpoClipEpsilon => ppoClipEpsilon;
    public float RewardClipSigma => rewardClipSigma;
    public float CriticLearningRate => criticLearningRate;
    public float CriticHuberDelta => criticHuberDelta;
    public float ExplorationEpsilonScale => explorationEpsilonScale;
    public float EpsilonDecayPerStep => epsilonDecayPerStep;
    public float MinEpsilon => minEpsilon;
    public float MinLearningRate => minLearningRate;
    public float LrDecayPerSecond => lrDecayPerSecond;
    public float FitnessSurvivalWeight => fitnessSurvivalWeight;
    public float FitnessSurvivalTau => fitnessSurvivalTau;
    public float FitnessRateWindow => fitnessRateWindow;
    public float FitnessMinLifetime => fitnessMinLifetime;
    public float FitnessFoodRateWeight => fitnessFoodRateWeight;
    public float FitnessReproduceRateWeight => fitnessReproduceRateWeight;
    public float FitnessDamageRateWeight => fitnessDamageRateWeight;
    public float TerminalFitnessSensitivity => terminalFitnessSensitivity;
    public float TerminalPenaltyMinScale => terminalPenaltyMinScale;
    public float TerminalPenaltyMaxScale => terminalPenaltyMaxScale;
    public int TournamentSize => tournamentSize;
    public float GenerationInterval => generationInterval;
    public float EliteFraction => eliteFraction;
    public float BasalEnergyDrain => basalEnergyDrain;
    public float TerrainBiasWeight => terrainBiasWeight;
    public float TerrainCostWeight => terrainCostWeight;
    public float TerrainSlopeWeight => terrainSlopeWeight;
    public float TerrainWaterWeight => terrainWaterWeight;
    public float MaxCycleDt => maxCycleDt;
    public float ModifierDecayTau => modifierDecayTau;
    public float EatRange => eatRange;
    public float InfeasibleActionHealthPenalty => infeasibleActionHealthPenalty;
    public float ThreatenDuration => threatenDuration;
    public float ShareFoodDuration => shareFoodDuration;
    public float CommandWatchdogGrace => commandWatchdogGrace;
    public float RewardStdFloor => rewardStdFloor;
    public float RestHealEnergyCost => restHealEnergyCost;
    public float SpeechEnergyCost => speechEnergyCost;
    public float ThreatenEnergyCost => threatenEnergyCost;
    public float DangerLowFraction => dangerLowFraction;
    public float DangerMidFraction => dangerMidFraction;
    public float DangerCritFraction => dangerCritFraction;
    public float BreedMarginFraction => breedMarginFraction;
    public float ShareFoodTransferFraction => shareFoodTransferFraction;
    public float ShareFoodVictimRatio => shareFoodVictimRatio;
    public float FleeDistanceMul => fleeDistanceMul;
    public float RememberPointMinSpacing => rememberPointMinSpacing;
    public float ThreatenRangeMul => threatenRangeMul;
    public float GeneSpeedCostExponent => geneSpeedCostExponent;
    public float GeneEnergyCapacityUpkeep => geneEnergyCapacityUpkeep;
    public float GeneDetectionUpkeep => geneDetectionUpkeep;
    public float GeneMinBasalMul => geneMinBasalMul;
    public float InitBiasRange => initBiasRange;
    public bool PeriodicGenotypeOverwrite => periodicGenotypeOverwrite;
    public float CodonsPerSecond => codonsPerSecond;
    public int MaxCodonsPerCycle => maxCodonsPerCycle;
    public int DormantCodons => dormantCodons;
    public float ContactRadius => contactRadius;
    public float IntegrityDecayPerSecond => integrityDecayPerSecond;
    public float IntegrityMutationScale => integrityMutationScale;
    public float IntegrityRemoveThreshold => integrityRemoveThreshold;
    public float VerticalTransmissionChance => verticalTransmissionChance;
    public float VerticalEndogenousMutationRate => verticalEndogenousMutationRate;
    public float VerticalTableMutationChance => verticalTableMutationChance;
    public int VirologyMaxSegments => virologyMaxSegments;
    public int RndSamplesPerSweep => rndSamplesPerSweep;
    public float RndLearningRate => rndLearningRate;
    public float RndNormAlpha => rndNormAlpha;
    public float EpsilonPlateauFitnessThreshold => epsilonPlateauFitnessThreshold;
    public float EpsilonPlateauDrop => epsilonPlateauDrop;
    public float EpsilonPlateauMinScale => epsilonPlateauMinScale;
    public float EpsilonPlateauThresholdGrowth => epsilonPlateauThresholdGrowth;
    public float EpsilonPlateauThresholdStep => epsilonPlateauThresholdStep;
    public float ActionTraceHorizon => actionTraceHorizon;
    public float ReservoirSpectralRadius => reservoirSpectralRadius;
    public float ReservoirHz => reservoirHz;
    public float TranslationLutMaxDistanceSq => translationLutMaxDistanceSq;
    public float BlockedSpeedThreshold => blockedSpeedThreshold;
    public float BlockedSeconds => blockedSeconds;
    public float DigestRateRest => digestRateRest;
    public float DigestRateActive => digestRateActive;
    public float DigestEffRest => digestEffRest;
    public float DigestEffActive => digestEffActive;
    public float StomachCapacityFraction => stomachCapacityFraction;
    public float WellFedGainPerSecond => wellFedGainPerSecond;
    public float WellFedDecayPerSecond => wellFedDecayPerSecond;
    public float WellFedBasalReduction => wellFedBasalReduction;
    public float DriveEnergyWeight => driveEnergyWeight;
    public float DriveHealthWeight => driveHealthWeight;
    public float DriveRewardWeight => driveRewardWeight;
    public float DriveShapingWeight => driveShapingWeight;
    public float EventReproduceReward => eventReproduceReward;
    public float InfeasibleActionReward => infeasibleActionReward;
    public float GoalFoodWeight => goalFoodWeight;
    public float GoalEnergyWeight => goalEnergyWeight;
    public float GoalRestWeight => goalRestWeight;
    public float CoordCuriosityWeight => coordCuriosityWeight;
    public float ExecGammaPerSecond => execGammaPerSecond;
    public float CoordGammaPerSecond => coordGammaPerSecond;
    public float SynergyWindow => synergyWindow;
    public float RestAfterEatDigestMul => restAfterEatDigestMul;
    public float NestRestHealMul => nestRestHealMul;
    public float NestRestDamageMul => nestRestDamageMul;
    public float NightStart => nightStart;
    public float NightEnd => nightEnd;
    public float NightOutsideDrainMul => nightOutsideDrainMul;
    public float ThreatenAttackMul => threatenAttackMul;
    public float GroupAttackBonus => groupAttackBonus;
    public float GroupAttackRadius => groupAttackRadius;
    public float GroupAttackWindow => groupAttackWindow;
    public int GroupAttackMaxCount => groupAttackMaxCount;
    public float WarnWindow => warnWindow;
    public float WarnDangerThreshold => warnDangerThreshold;
    public float WarnedFleeSpeedMul => warnedFleeSpeedMul;
    public float SpeechRadius => speechRadius;
    public float MovePauseMin => movePauseMin;
    public float MovePauseMax => movePauseMax;
    public float AttackMoveMaxDuration => attackMoveMaxDuration;
    public float FoodMinNutritionFraction => foodMinNutritionFraction;
    public float FoodMaturityPerSecond => foodMaturityPerSecond;
    public float FoodGrowthRate => foodGrowthRate;
    public float FoodSeedFraction => foodSeedFraction;
    public float FoodChunkCapacity => foodChunkCapacity;
    public float SeasonAmplitude => seasonAmplitude;
    public float SeasonPeriod => seasonPeriod;
    public float EcologyTickInterval => ecologyTickInterval;
    public float EcologyMaxStep => ecologyMaxStep;
    public float LargeFoodChance => largeFoodChance;
    public float LargeFoodEnergy => largeFoodEnergy;
    public float LargeFoodWindow => largeFoodWindow;
    public float ToxicNutritionMul => toxicNutritionMul;
    public float ToxicDamage => toxicDamage;
    public float EatSecondsPerEnergy => eatSecondsPerEnergy;
    public float CorpseMinEnergy => corpseMinEnergy;
    public int CorpseSearchCells => corpseSearchCells;
    public float CorpseSpoilTau => corpseSpoilTau;
    public float NestEatPortion => nestEatPortion;
    public float NestStorageNorm => nestStorageNorm;
    public float CarrySpeedMul => carrySpeedMul;
    public int PlannerCandidates => plannerCandidates;
    public float PlannerSectorHalf => plannerSectorHalf;
    public float PlannerMinRadiusFraction => plannerMinRadiusFraction;
    public float PlannerMoveCostWeight => plannerMoveCostWeight;
    public float PlannerFoodWeight => plannerFoodWeight;
    public float PlannerDangerWeight => plannerDangerWeight;
    public float PlannerTargetWeight => plannerTargetWeight;
    public float PlannerAlignWeight => plannerAlignWeight;
    public float PlannerCurvatureMin => plannerCurvatureMin;
    public float PlannerCurvatureScale => plannerCurvatureScale;
    public float PlannerRadiusMax => plannerRadiusMax;
    public int PlannerMaxReplans => plannerMaxReplans;
    public float PlannerReplanAngle => plannerReplanAngle;
    public float NestRadius => nestRadius;
    public int NestMapSize => nestMapSize;
    public float NestMapCellSize => nestMapCellSize;
    public float NestMapMaxValue => nestMapMaxValue;
    public float ColonyChannelTau(int channel)
        => colonyChannelTau != null && (uint)channel < (uint)colonyChannelTau.Length
            ? colonyChannelTau[channel]
            : colonyChannelDefaultTau;
    public float NestFoodPeakMin => nestFoodPeakMin;
    public float NestFoodMark => nestFoodMark;
    public float NestDangerMark => nestDangerMark;
    public float AlarmTau => alarmTau;
    public int AlarmHuntMinMembers => alarmHuntMinMembers;
    public float AlarmFromDamage => alarmFromDamage;
    public float AlarmHuntBias => alarmHuntBias;
    public float AlarmSurviveBias => alarmSurviveBias;
    public float AlarmFleeBias => alarmFleeBias;
    public float SkipWeakHpFraction => skipWeakHpFraction;
    public int SkipCrowdCount => skipCrowdCount;
    public float CrowdRadius => crowdRadius;
    public float SpeechSpreadRadius => speechSpreadRadius;
    public float BiteTransmissionChance => biteTransmissionChance;
    public int ImmuneMemorySize => immuneMemorySize;
    public int ImmuneHammingThreshold => immuneHammingThreshold;
    public float FeverIntegrityMul => feverIntegrityMul;
    public float FeverDrainMul => feverDrainMul;
    public int CaptureLength => captureLength;
    public float CarryPoiThreshold => carryPoiThreshold;
    public float BlindStrength => blindStrength;
    public float FrenzyDamageMul => frenzyDamageMul;
    public float FrenzyHuntBias => frenzyHuntBias;
    public float FrenzyFleeSuppress => frenzyFleeSuppress;
    public float LethargySlow => lethargySlow;
    public int   EpsilonScheduleMode => (int)epsilonScheduleMode;

    public float BiomeFertility(int biome) => BiomeValue(biomeFertility, biome, 1f);
    public float BiomeToxicity(int biome)  => BiomeValue(biomeToxicity, biome, 0f);

    private static float BiomeValue(float[] table, int biome, float fallback)
    {
        if (table == null || table.Length == 0) return fallback;
        int i = biome < 0 ? 0 : biome & 3;
        return i < table.Length ? table[i] : fallback;
    }

    private static SimulationRules _active;

    public static SimulationRules Active
    {
        get
        {
            if (_active == null) _active = CreateInstance<SimulationRules>();
            return _active;
        }
    }
}
